# -*- coding: utf-8 -*-
"""Searchquery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vqm2T1IFFubKdZ9XFa893eJT-xyBvsS
"""



"""#Design Query Embedding for searching shopping products

Example: "iphone charger"      ↔ "lightning cable"

"wireless earbuds"    ↔ "bluetooth earphones"

Prepare Training data using previous shopping data:

| Query            | Clicked Product       |
| ---------------- | --------------------- |
| iphone charger   | Apple Lightning Cable |
| iphone charger   | Anker Charger         |
| wireless earbuds | Sony Earbuds          |


Then, create training triplets:

Anchor Query      Positive Product        Negative Product

----------------------------------------------------------------


iphone charger    Apple Charger           Nike Shoes

iphone charger    Anker Charger           Samsung TV

wireless earbuds  Sony Earbuds            Coffee Mug
"""



#iphone charger ↔ lightning cable = similar
#iphone charger ↔ running shoes = dissimilar

"""Training from scratch with Triplet Loss
Idea

We train using:

Anchor (A)
Positive (P)
Negative (N)

Example:

A = "iphone charger"
P = "lightning cable"
N = "running shoes"

We want:

distance(A,P) << distance(A,N)
Triplet Loss Formula
L=max(0,d(A,P)−d(A,N)+m)

Anchor ----- Positive

Anchor ------------------------ Negative
"""

from transformers import AutoTokenizer, AutoModel
import torch
import torch.nn as nn

# -------------------------
# Model
# -------------------------
tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

encoder = AutoModel.from_pretrained(
    "bert-base-uncased"
)

triplet_loss = nn.TripletMarginLoss(
    margin=0.5
)

optimizer = torch.optim.Adam(
    encoder.parameters(),
    lr=1e-4
)

# -------------------------
# Training data
# -------------------------
anchor_text = [
    "iphone charger",
    "wireless earbuds",
    "laptop sleeve",
    "coffee maker",
    "running shoes",
    "gaming keyboard",
    "usb cable",
    "water bottle"
]

positive_text = [
    "lightning cable",
    "bluetooth earphones",
    "macbook case",
    "espresso machine",
    "sports shoes",
    "mechanical keyboard",
    "charging cable",
    "insulated bottle"
]

negative_text = [
    "running shoes",
    "coffee mug",
    "dog food",
    "iphone case",
    "wireless mouse",
    "kitchen knife",
    "water bottle",
    "gaming monitor"
]

# -------------------------
# Tokenize once
# -------------------------
anchor_inputs = tokenizer(
    anchor_text,
    padding=True,
    truncation=True,
    return_tensors="pt"
)
print("Positive tokens are",anchor_inputs)

positive_inputs = tokenizer(
    positive_text,
    padding=True,
    truncation=True,
    return_tensors="pt"
)

negative_inputs = tokenizer(
    negative_text,
    padding=True,
    truncation=True,
    return_tensors="pt"
)

# -------------------------
# Training loop
# -------------------------
for epoch in range(20):

    optimizer.zero_grad()

    anchor_emb = encoder(
        **anchor_inputs
    ).last_hidden_state[:, 0, :]

    positive_emb = encoder(
        **positive_inputs
    ).last_hidden_state[:, 0, :]

    negative_emb = encoder(
        **negative_inputs
    ).last_hidden_state[:, 0, :]

    loss = triplet_loss(
        anchor_emb,
        positive_emb,
        negative_emb
    )

    loss.backward()
    optimizer.step()

    d_pos = torch.norm(
        anchor_emb - positive_emb,
        dim=1
    ).mean()

    d_neg = torch.norm(
        anchor_emb - negative_emb,
        dim=1
    ).mean()

    print(
        f"Epoch {epoch+1:2d} | "
        f"Loss={loss.item():.4f} | "
        f"d_pos={d_pos.item():.4f} | "
        f"d_neg={d_neg.item():.4f}"
    )





